server:
  port: 8080
  error:
    whitelabel:
    include-stacktrace: always
security.jwt:
  tokenExpirationTime: 1440
  refreshTokenExpTime: 10080
  tokenIssuer: Food Delivery Corp.
  tokenSigningKey: sao32iufns3295a
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery?useSSL=false
    username: food_delivery
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.yandex.ru
    port: 465
    username: food.delivery.corp
    password: 3to2dajnm29ykQ7
    protocol: smtps
    properties:
      mail:
        smtps:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
