export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// export const CHECK_IS_EMAIL_OCCUPIED_START = "CHECK_IS_EMAIL_OCCUPIED_START";
// export const CHECK_IS_EMAIL_OCCUPIED_SUCCESS = "CHECK_IS_EMAIL_OCCUPIED_SUCCESS";
// export const CHECK_IS_EMAIL_OCCUPIED_ERROR = "CHECK_IS_EMAIL_OCCUPIED_ERROR";
